/// Flutter icons Drumstickmobile
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Drumstickmobile
///      fonts:
///       - asset: fonts/Drumstickmobile.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Drumstickmobile {
  Drumstickmobile._();

  static const _kFontFam = 'Drumstickmobile';
  static const _kFontPkg = null;

  static const IconData drum = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
